name: movie_hub
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  velocity_x: ^4.1.1
  nav: ^1.4.2
  http: ^1.1.0
  url_launcher: ^6.1.14
  flutter_rating_bar: ^4.0.1
  dio: ^5.3.3
  retrofit: ^4.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  freezed: ^2.4.3

flutter:
  uses-material-design: true

